/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bliss.service.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EEventUserGroup implements org.apache.thrift.TEnum {
  ALL_USERS(0),
  NEW_USER(1),
  FREE_USER(2),
  PAID_PAID(3),
  VIP_USER(4);

  private final int value;

  private EEventUserGroup(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EEventUserGroup findByValue(int value) { 
    switch (value) {
      case 0:
        return ALL_USERS;
      case 1:
        return NEW_USER;
      case 2:
        return FREE_USER;
      case 3:
        return PAID_PAID;
      case 4:
        return VIP_USER;
      default:
        return null;
    }
  }
}
