/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vn.nct.cardgame.profile.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TGuestResult implements org.apache.thrift.TEnum {
  SUCCESS(0),
  SYS_ERROR(1),
  DATA_UNVALID(2),
  GUEST_LINKED(3),
  USERNAME_DUPLICATED(4);

  private final int value;

  private TGuestResult(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TGuestResult findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case 1:
        return SYS_ERROR;
      case 2:
        return DATA_UNVALID;
      case 3:
        return GUEST_LINKED;
      case 4:
        return USERNAME_DUPLICATED;
      default:
        return null;
    }
  }
}
