/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vn.nct.cardgame.profile.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TUserPromotionList implements org.apache.thrift.TBase<TUserPromotionList, TUserPromotionList._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TUserPromotionList");

  private static final org.apache.thrift.protocol.TField MAP_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("mapData", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TUserPromotionListStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TUserPromotionListTupleSchemeFactory());
  }

  public Map<Integer,TPromotion> mapData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAP_DATA((short)1, "mapData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAP_DATA
          return MAP_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAP_DATA, new org.apache.thrift.meta_data.FieldMetaData("mapData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TPromotion.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TUserPromotionList.class, metaDataMap);
  }

  public TUserPromotionList() {
  }

  public TUserPromotionList(
    Map<Integer,TPromotion> mapData)
  {
    this();
    this.mapData = mapData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TUserPromotionList(TUserPromotionList other) {
    if (other.isSetMapData()) {
      Map<Integer,TPromotion> __this__mapData = new HashMap<Integer,TPromotion>();
      for (Map.Entry<Integer, TPromotion> other_element : other.mapData.entrySet()) {

        Integer other_element_key = other_element.getKey();
        TPromotion other_element_value = other_element.getValue();

        Integer __this__mapData_copy_key = other_element_key;

        TPromotion __this__mapData_copy_value = new TPromotion(other_element_value);

        __this__mapData.put(__this__mapData_copy_key, __this__mapData_copy_value);
      }
      this.mapData = __this__mapData;
    }
  }

  public TUserPromotionList deepCopy() {
    return new TUserPromotionList(this);
  }

  @Override
  public void clear() {
    this.mapData = null;
  }

  public int getMapDataSize() {
    return (this.mapData == null) ? 0 : this.mapData.size();
  }

  public void putToMapData(int key, TPromotion val) {
    if (this.mapData == null) {
      this.mapData = new HashMap<Integer,TPromotion>();
    }
    this.mapData.put(key, val);
  }

  public Map<Integer,TPromotion> getMapData() {
    return this.mapData;
  }

  public TUserPromotionList setMapData(Map<Integer,TPromotion> mapData) {
    this.mapData = mapData;
    return this;
  }

  public void unsetMapData() {
    this.mapData = null;
  }

  /** Returns true if field mapData is set (has been assigned a value) and false otherwise */
  public boolean isSetMapData() {
    return this.mapData != null;
  }

  public void setMapDataIsSet(boolean value) {
    if (!value) {
      this.mapData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MAP_DATA:
      if (value == null) {
        unsetMapData();
      } else {
        setMapData((Map<Integer,TPromotion>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MAP_DATA:
      return getMapData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MAP_DATA:
      return isSetMapData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TUserPromotionList)
      return this.equals((TUserPromotionList)that);
    return false;
  }

  public boolean equals(TUserPromotionList that) {
    if (that == null)
      return false;

    boolean this_present_mapData = true && this.isSetMapData();
    boolean that_present_mapData = true && that.isSetMapData();
    if (this_present_mapData || that_present_mapData) {
      if (!(this_present_mapData && that_present_mapData))
        return false;
      if (!this.mapData.equals(that.mapData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TUserPromotionList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TUserPromotionList typedOther = (TUserPromotionList)other;

    lastComparison = Boolean.valueOf(isSetMapData()).compareTo(typedOther.isSetMapData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMapData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mapData, typedOther.mapData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TUserPromotionList(");
    boolean first = true;

    sb.append("mapData:");
    if (this.mapData == null) {
      sb.append("null");
    } else {
      sb.append(this.mapData);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TUserPromotionListStandardSchemeFactory implements SchemeFactory {
    public TUserPromotionListStandardScheme getScheme() {
      return new TUserPromotionListStandardScheme();
    }
  }

  private static class TUserPromotionListStandardScheme extends StandardScheme<TUserPromotionList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TUserPromotionList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAP_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map16 = iprot.readMapBegin();
                struct.mapData = new HashMap<Integer,TPromotion>(2*_map16.size);
                for (int _i17 = 0; _i17 < _map16.size; ++_i17)
                {
                  int _key18; // required
                  TPromotion _val19; // required
                  _key18 = iprot.readI32();
                  _val19 = new TPromotion();
                  _val19.read(iprot);
                  struct.mapData.put(_key18, _val19);
                }
                iprot.readMapEnd();
              }
              struct.setMapDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TUserPromotionList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.mapData != null) {
        oprot.writeFieldBegin(MAP_DATA_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, struct.mapData.size()));
          for (Map.Entry<Integer, TPromotion> _iter20 : struct.mapData.entrySet())
          {
            oprot.writeI32(_iter20.getKey());
            _iter20.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TUserPromotionListTupleSchemeFactory implements SchemeFactory {
    public TUserPromotionListTupleScheme getScheme() {
      return new TUserPromotionListTupleScheme();
    }
  }

  private static class TUserPromotionListTupleScheme extends TupleScheme<TUserPromotionList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TUserPromotionList struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMapData()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMapData()) {
        {
          oprot.writeI32(struct.mapData.size());
          for (Map.Entry<Integer, TPromotion> _iter21 : struct.mapData.entrySet())
          {
            oprot.writeI32(_iter21.getKey());
            _iter21.getValue().write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TUserPromotionList struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map22 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.mapData = new HashMap<Integer,TPromotion>(2*_map22.size);
          for (int _i23 = 0; _i23 < _map22.size; ++_i23)
          {
            int _key24; // required
            TPromotion _val25; // required
            _key24 = iprot.readI32();
            _val25 = new TPromotion();
            _val25.read(iprot);
            struct.mapData.put(_key24, _val25);
          }
        }
        struct.setMapDataIsSet(true);
      }
    }
  }

}

