/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bliss.service.paymentv2.thrift;

public enum EProductType implements org.apache.thrift.TEnum {
  INAPP(0),
  CARD(1),
  SMS(2);

  private final int value;

  private EProductType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EProductType findByValue(int value) { 
    switch (value) {
      case 0:
        return INAPP;
      case 1:
        return CARD;
      case 2:
        return SMS;
      default:
        return null;
    }
  }
}
