/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bliss.service.paymentv2.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TPromotionValue implements org.apache.thrift.TBase<TPromotionValue, TPromotionValue._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TPromotionValue");

  private static final org.apache.thrift.protocol.TField PROMOTION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("promotionId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PROMOTION_RATE_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("promotionRateData", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PROMOTION_USER_GROUP_FIELD_DESC = new org.apache.thrift.protocol.TField("promotionUserGroup", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField PROMOTION_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("promotionName", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PRIORITY_FIELD_DESC = new org.apache.thrift.protocol.TField("priority", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("description", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField DATE_BEGIN_FIELD_DESC = new org.apache.thrift.protocol.TField("dateBegin", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField DATE_END_FIELD_DESC = new org.apache.thrift.protocol.TField("dateEnd", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField DATE_CREATED_FIELD_DESC = new org.apache.thrift.protocol.TField("dateCreated", org.apache.thrift.protocol.TType.I64, (short)10);
  private static final org.apache.thrift.protocol.TField USER_CREATED_FIELD_DESC = new org.apache.thrift.protocol.TField("userCreated", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField DATE_MODIFIED_FIELD_DESC = new org.apache.thrift.protocol.TField("dateModified", org.apache.thrift.protocol.TType.I64, (short)12);
  private static final org.apache.thrift.protocol.TField USER_MODIFIED_FIELD_DESC = new org.apache.thrift.protocol.TField("userModified", org.apache.thrift.protocol.TType.STRING, (short)13);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TPromotionValueStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TPromotionValueTupleSchemeFactory());
  }

  public int promotionId; // required
  public String promotionRateData; // required
  /**
   * 
   * @see com.bliss.service.thrift.EEventUserGroup
   */
  public com.bliss.service.thrift.EEventUserGroup promotionUserGroup; // required
  public String promotionName; // required
  public int priority; // required
  public String description; // required
  /**
   * 
   * @see EStatus
   */
  public EStatus status; // required
  public long dateBegin; // required
  public long dateEnd; // required
  public long dateCreated; // required
  public String userCreated; // required
  public long dateModified; // required
  public String userModified; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PROMOTION_ID((short)1, "promotionId"),
    PROMOTION_RATE_DATA((short)2, "promotionRateData"),
    /**
     * 
     * @see com.bliss.service.thrift.EEventUserGroup
     */
    PROMOTION_USER_GROUP((short)3, "promotionUserGroup"),
    PROMOTION_NAME((short)4, "promotionName"),
    PRIORITY((short)5, "priority"),
    DESCRIPTION((short)6, "description"),
    /**
     * 
     * @see EStatus
     */
    STATUS((short)7, "status"),
    DATE_BEGIN((short)8, "dateBegin"),
    DATE_END((short)9, "dateEnd"),
    DATE_CREATED((short)10, "dateCreated"),
    USER_CREATED((short)11, "userCreated"),
    DATE_MODIFIED((short)12, "dateModified"),
    USER_MODIFIED((short)13, "userModified");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROMOTION_ID
          return PROMOTION_ID;
        case 2: // PROMOTION_RATE_DATA
          return PROMOTION_RATE_DATA;
        case 3: // PROMOTION_USER_GROUP
          return PROMOTION_USER_GROUP;
        case 4: // PROMOTION_NAME
          return PROMOTION_NAME;
        case 5: // PRIORITY
          return PRIORITY;
        case 6: // DESCRIPTION
          return DESCRIPTION;
        case 7: // STATUS
          return STATUS;
        case 8: // DATE_BEGIN
          return DATE_BEGIN;
        case 9: // DATE_END
          return DATE_END;
        case 10: // DATE_CREATED
          return DATE_CREATED;
        case 11: // USER_CREATED
          return USER_CREATED;
        case 12: // DATE_MODIFIED
          return DATE_MODIFIED;
        case 13: // USER_MODIFIED
          return USER_MODIFIED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PROMOTIONID_ISSET_ID = 0;
  private static final int __PRIORITY_ISSET_ID = 1;
  private static final int __DATEBEGIN_ISSET_ID = 2;
  private static final int __DATEEND_ISSET_ID = 3;
  private static final int __DATECREATED_ISSET_ID = 4;
  private static final int __DATEMODIFIED_ISSET_ID = 5;
  private BitSet __isset_bit_vector = new BitSet(6);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROMOTION_ID, new org.apache.thrift.meta_data.FieldMetaData("promotionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PROMOTION_RATE_DATA, new org.apache.thrift.meta_data.FieldMetaData("promotionRateData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROMOTION_USER_GROUP, new org.apache.thrift.meta_data.FieldMetaData("promotionUserGroup", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.bliss.service.thrift.EEventUserGroup.class)));
    tmpMap.put(_Fields.PROMOTION_NAME, new org.apache.thrift.meta_data.FieldMetaData("promotionName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRIORITY, new org.apache.thrift.meta_data.FieldMetaData("priority", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("description", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, EStatus.class)));
    tmpMap.put(_Fields.DATE_BEGIN, new org.apache.thrift.meta_data.FieldMetaData("dateBegin", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DATE_END, new org.apache.thrift.meta_data.FieldMetaData("dateEnd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DATE_CREATED, new org.apache.thrift.meta_data.FieldMetaData("dateCreated", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USER_CREATED, new org.apache.thrift.meta_data.FieldMetaData("userCreated", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATE_MODIFIED, new org.apache.thrift.meta_data.FieldMetaData("dateModified", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USER_MODIFIED, new org.apache.thrift.meta_data.FieldMetaData("userModified", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TPromotionValue.class, metaDataMap);
  }

  public TPromotionValue() {
  }

  public TPromotionValue(
    int promotionId,
    String promotionRateData,
    com.bliss.service.thrift.EEventUserGroup promotionUserGroup,
    String promotionName,
    int priority,
    String description,
    EStatus status,
    long dateBegin,
    long dateEnd,
    long dateCreated,
    String userCreated,
    long dateModified,
    String userModified)
  {
    this();
    this.promotionId = promotionId;
    setPromotionIdIsSet(true);
    this.promotionRateData = promotionRateData;
    this.promotionUserGroup = promotionUserGroup;
    this.promotionName = promotionName;
    this.priority = priority;
    setPriorityIsSet(true);
    this.description = description;
    this.status = status;
    this.dateBegin = dateBegin;
    setDateBeginIsSet(true);
    this.dateEnd = dateEnd;
    setDateEndIsSet(true);
    this.dateCreated = dateCreated;
    setDateCreatedIsSet(true);
    this.userCreated = userCreated;
    this.dateModified = dateModified;
    setDateModifiedIsSet(true);
    this.userModified = userModified;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TPromotionValue(TPromotionValue other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.promotionId = other.promotionId;
    if (other.isSetPromotionRateData()) {
      this.promotionRateData = other.promotionRateData;
    }
    if (other.isSetPromotionUserGroup()) {
      this.promotionUserGroup = other.promotionUserGroup;
    }
    if (other.isSetPromotionName()) {
      this.promotionName = other.promotionName;
    }
    this.priority = other.priority;
    if (other.isSetDescription()) {
      this.description = other.description;
    }
    if (other.isSetStatus()) {
      this.status = other.status;
    }
    this.dateBegin = other.dateBegin;
    this.dateEnd = other.dateEnd;
    this.dateCreated = other.dateCreated;
    if (other.isSetUserCreated()) {
      this.userCreated = other.userCreated;
    }
    this.dateModified = other.dateModified;
    if (other.isSetUserModified()) {
      this.userModified = other.userModified;
    }
  }

  public TPromotionValue deepCopy() {
    return new TPromotionValue(this);
  }

  @Override
  public void clear() {
    setPromotionIdIsSet(false);
    this.promotionId = 0;
    this.promotionRateData = null;
    this.promotionUserGroup = null;
    this.promotionName = null;
    setPriorityIsSet(false);
    this.priority = 0;
    this.description = null;
    this.status = null;
    setDateBeginIsSet(false);
    this.dateBegin = 0;
    setDateEndIsSet(false);
    this.dateEnd = 0;
    setDateCreatedIsSet(false);
    this.dateCreated = 0;
    this.userCreated = null;
    setDateModifiedIsSet(false);
    this.dateModified = 0;
    this.userModified = null;
  }

  public int getPromotionId() {
    return this.promotionId;
  }

  public TPromotionValue setPromotionId(int promotionId) {
    this.promotionId = promotionId;
    setPromotionIdIsSet(true);
    return this;
  }

  public void unsetPromotionId() {
    __isset_bit_vector.clear(__PROMOTIONID_ISSET_ID);
  }

  /** Returns true if field promotionId is set (has been assigned a value) and false otherwise */
  public boolean isSetPromotionId() {
    return __isset_bit_vector.get(__PROMOTIONID_ISSET_ID);
  }

  public void setPromotionIdIsSet(boolean value) {
    __isset_bit_vector.set(__PROMOTIONID_ISSET_ID, value);
  }

  public String getPromotionRateData() {
    return this.promotionRateData;
  }

  public TPromotionValue setPromotionRateData(String promotionRateData) {
    this.promotionRateData = promotionRateData;
    return this;
  }

  public void unsetPromotionRateData() {
    this.promotionRateData = null;
  }

  /** Returns true if field promotionRateData is set (has been assigned a value) and false otherwise */
  public boolean isSetPromotionRateData() {
    return this.promotionRateData != null;
  }

  public void setPromotionRateDataIsSet(boolean value) {
    if (!value) {
      this.promotionRateData = null;
    }
  }

  /**
   * 
   * @see com.bliss.service.thrift.EEventUserGroup
   */
  public com.bliss.service.thrift.EEventUserGroup getPromotionUserGroup() {
    return this.promotionUserGroup;
  }

  /**
   * 
   * @see com.bliss.service.thrift.EEventUserGroup
   */
  public TPromotionValue setPromotionUserGroup(com.bliss.service.thrift.EEventUserGroup promotionUserGroup) {
    this.promotionUserGroup = promotionUserGroup;
    return this;
  }

  public void unsetPromotionUserGroup() {
    this.promotionUserGroup = null;
  }

  /** Returns true if field promotionUserGroup is set (has been assigned a value) and false otherwise */
  public boolean isSetPromotionUserGroup() {
    return this.promotionUserGroup != null;
  }

  public void setPromotionUserGroupIsSet(boolean value) {
    if (!value) {
      this.promotionUserGroup = null;
    }
  }

  public String getPromotionName() {
    return this.promotionName;
  }

  public TPromotionValue setPromotionName(String promotionName) {
    this.promotionName = promotionName;
    return this;
  }

  public void unsetPromotionName() {
    this.promotionName = null;
  }

  /** Returns true if field promotionName is set (has been assigned a value) and false otherwise */
  public boolean isSetPromotionName() {
    return this.promotionName != null;
  }

  public void setPromotionNameIsSet(boolean value) {
    if (!value) {
      this.promotionName = null;
    }
  }

  public int getPriority() {
    return this.priority;
  }

  public TPromotionValue setPriority(int priority) {
    this.priority = priority;
    setPriorityIsSet(true);
    return this;
  }

  public void unsetPriority() {
    __isset_bit_vector.clear(__PRIORITY_ISSET_ID);
  }

  /** Returns true if field priority is set (has been assigned a value) and false otherwise */
  public boolean isSetPriority() {
    return __isset_bit_vector.get(__PRIORITY_ISSET_ID);
  }

  public void setPriorityIsSet(boolean value) {
    __isset_bit_vector.set(__PRIORITY_ISSET_ID, value);
  }

  public String getDescription() {
    return this.description;
  }

  public TPromotionValue setDescription(String description) {
    this.description = description;
    return this;
  }

  public void unsetDescription() {
    this.description = null;
  }

  /** Returns true if field description is set (has been assigned a value) and false otherwise */
  public boolean isSetDescription() {
    return this.description != null;
  }

  public void setDescriptionIsSet(boolean value) {
    if (!value) {
      this.description = null;
    }
  }

  /**
   * 
   * @see EStatus
   */
  public EStatus getStatus() {
    return this.status;
  }

  /**
   * 
   * @see EStatus
   */
  public TPromotionValue setStatus(EStatus status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public long getDateBegin() {
    return this.dateBegin;
  }

  public TPromotionValue setDateBegin(long dateBegin) {
    this.dateBegin = dateBegin;
    setDateBeginIsSet(true);
    return this;
  }

  public void unsetDateBegin() {
    __isset_bit_vector.clear(__DATEBEGIN_ISSET_ID);
  }

  /** Returns true if field dateBegin is set (has been assigned a value) and false otherwise */
  public boolean isSetDateBegin() {
    return __isset_bit_vector.get(__DATEBEGIN_ISSET_ID);
  }

  public void setDateBeginIsSet(boolean value) {
    __isset_bit_vector.set(__DATEBEGIN_ISSET_ID, value);
  }

  public long getDateEnd() {
    return this.dateEnd;
  }

  public TPromotionValue setDateEnd(long dateEnd) {
    this.dateEnd = dateEnd;
    setDateEndIsSet(true);
    return this;
  }

  public void unsetDateEnd() {
    __isset_bit_vector.clear(__DATEEND_ISSET_ID);
  }

  /** Returns true if field dateEnd is set (has been assigned a value) and false otherwise */
  public boolean isSetDateEnd() {
    return __isset_bit_vector.get(__DATEEND_ISSET_ID);
  }

  public void setDateEndIsSet(boolean value) {
    __isset_bit_vector.set(__DATEEND_ISSET_ID, value);
  }

  public long getDateCreated() {
    return this.dateCreated;
  }

  public TPromotionValue setDateCreated(long dateCreated) {
    this.dateCreated = dateCreated;
    setDateCreatedIsSet(true);
    return this;
  }

  public void unsetDateCreated() {
    __isset_bit_vector.clear(__DATECREATED_ISSET_ID);
  }

  /** Returns true if field dateCreated is set (has been assigned a value) and false otherwise */
  public boolean isSetDateCreated() {
    return __isset_bit_vector.get(__DATECREATED_ISSET_ID);
  }

  public void setDateCreatedIsSet(boolean value) {
    __isset_bit_vector.set(__DATECREATED_ISSET_ID, value);
  }

  public String getUserCreated() {
    return this.userCreated;
  }

  public TPromotionValue setUserCreated(String userCreated) {
    this.userCreated = userCreated;
    return this;
  }

  public void unsetUserCreated() {
    this.userCreated = null;
  }

  /** Returns true if field userCreated is set (has been assigned a value) and false otherwise */
  public boolean isSetUserCreated() {
    return this.userCreated != null;
  }

  public void setUserCreatedIsSet(boolean value) {
    if (!value) {
      this.userCreated = null;
    }
  }

  public long getDateModified() {
    return this.dateModified;
  }

  public TPromotionValue setDateModified(long dateModified) {
    this.dateModified = dateModified;
    setDateModifiedIsSet(true);
    return this;
  }

  public void unsetDateModified() {
    __isset_bit_vector.clear(__DATEMODIFIED_ISSET_ID);
  }

  /** Returns true if field dateModified is set (has been assigned a value) and false otherwise */
  public boolean isSetDateModified() {
    return __isset_bit_vector.get(__DATEMODIFIED_ISSET_ID);
  }

  public void setDateModifiedIsSet(boolean value) {
    __isset_bit_vector.set(__DATEMODIFIED_ISSET_ID, value);
  }

  public String getUserModified() {
    return this.userModified;
  }

  public TPromotionValue setUserModified(String userModified) {
    this.userModified = userModified;
    return this;
  }

  public void unsetUserModified() {
    this.userModified = null;
  }

  /** Returns true if field userModified is set (has been assigned a value) and false otherwise */
  public boolean isSetUserModified() {
    return this.userModified != null;
  }

  public void setUserModifiedIsSet(boolean value) {
    if (!value) {
      this.userModified = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PROMOTION_ID:
      if (value == null) {
        unsetPromotionId();
      } else {
        setPromotionId((Integer)value);
      }
      break;

    case PROMOTION_RATE_DATA:
      if (value == null) {
        unsetPromotionRateData();
      } else {
        setPromotionRateData((String)value);
      }
      break;

    case PROMOTION_USER_GROUP:
      if (value == null) {
        unsetPromotionUserGroup();
      } else {
        setPromotionUserGroup((com.bliss.service.thrift.EEventUserGroup)value);
      }
      break;

    case PROMOTION_NAME:
      if (value == null) {
        unsetPromotionName();
      } else {
        setPromotionName((String)value);
      }
      break;

    case PRIORITY:
      if (value == null) {
        unsetPriority();
      } else {
        setPriority((Integer)value);
      }
      break;

    case DESCRIPTION:
      if (value == null) {
        unsetDescription();
      } else {
        setDescription((String)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((EStatus)value);
      }
      break;

    case DATE_BEGIN:
      if (value == null) {
        unsetDateBegin();
      } else {
        setDateBegin((Long)value);
      }
      break;

    case DATE_END:
      if (value == null) {
        unsetDateEnd();
      } else {
        setDateEnd((Long)value);
      }
      break;

    case DATE_CREATED:
      if (value == null) {
        unsetDateCreated();
      } else {
        setDateCreated((Long)value);
      }
      break;

    case USER_CREATED:
      if (value == null) {
        unsetUserCreated();
      } else {
        setUserCreated((String)value);
      }
      break;

    case DATE_MODIFIED:
      if (value == null) {
        unsetDateModified();
      } else {
        setDateModified((Long)value);
      }
      break;

    case USER_MODIFIED:
      if (value == null) {
        unsetUserModified();
      } else {
        setUserModified((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PROMOTION_ID:
      return Integer.valueOf(getPromotionId());

    case PROMOTION_RATE_DATA:
      return getPromotionRateData();

    case PROMOTION_USER_GROUP:
      return getPromotionUserGroup();

    case PROMOTION_NAME:
      return getPromotionName();

    case PRIORITY:
      return Integer.valueOf(getPriority());

    case DESCRIPTION:
      return getDescription();

    case STATUS:
      return getStatus();

    case DATE_BEGIN:
      return Long.valueOf(getDateBegin());

    case DATE_END:
      return Long.valueOf(getDateEnd());

    case DATE_CREATED:
      return Long.valueOf(getDateCreated());

    case USER_CREATED:
      return getUserCreated();

    case DATE_MODIFIED:
      return Long.valueOf(getDateModified());

    case USER_MODIFIED:
      return getUserModified();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PROMOTION_ID:
      return isSetPromotionId();
    case PROMOTION_RATE_DATA:
      return isSetPromotionRateData();
    case PROMOTION_USER_GROUP:
      return isSetPromotionUserGroup();
    case PROMOTION_NAME:
      return isSetPromotionName();
    case PRIORITY:
      return isSetPriority();
    case DESCRIPTION:
      return isSetDescription();
    case STATUS:
      return isSetStatus();
    case DATE_BEGIN:
      return isSetDateBegin();
    case DATE_END:
      return isSetDateEnd();
    case DATE_CREATED:
      return isSetDateCreated();
    case USER_CREATED:
      return isSetUserCreated();
    case DATE_MODIFIED:
      return isSetDateModified();
    case USER_MODIFIED:
      return isSetUserModified();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TPromotionValue)
      return this.equals((TPromotionValue)that);
    return false;
  }

  public boolean equals(TPromotionValue that) {
    if (that == null)
      return false;

    boolean this_present_promotionId = true;
    boolean that_present_promotionId = true;
    if (this_present_promotionId || that_present_promotionId) {
      if (!(this_present_promotionId && that_present_promotionId))
        return false;
      if (this.promotionId != that.promotionId)
        return false;
    }

    boolean this_present_promotionRateData = true && this.isSetPromotionRateData();
    boolean that_present_promotionRateData = true && that.isSetPromotionRateData();
    if (this_present_promotionRateData || that_present_promotionRateData) {
      if (!(this_present_promotionRateData && that_present_promotionRateData))
        return false;
      if (!this.promotionRateData.equals(that.promotionRateData))
        return false;
    }

    boolean this_present_promotionUserGroup = true && this.isSetPromotionUserGroup();
    boolean that_present_promotionUserGroup = true && that.isSetPromotionUserGroup();
    if (this_present_promotionUserGroup || that_present_promotionUserGroup) {
      if (!(this_present_promotionUserGroup && that_present_promotionUserGroup))
        return false;
      if (!this.promotionUserGroup.equals(that.promotionUserGroup))
        return false;
    }

    boolean this_present_promotionName = true && this.isSetPromotionName();
    boolean that_present_promotionName = true && that.isSetPromotionName();
    if (this_present_promotionName || that_present_promotionName) {
      if (!(this_present_promotionName && that_present_promotionName))
        return false;
      if (!this.promotionName.equals(that.promotionName))
        return false;
    }

    boolean this_present_priority = true;
    boolean that_present_priority = true;
    if (this_present_priority || that_present_priority) {
      if (!(this_present_priority && that_present_priority))
        return false;
      if (this.priority != that.priority)
        return false;
    }

    boolean this_present_description = true && this.isSetDescription();
    boolean that_present_description = true && that.isSetDescription();
    if (this_present_description || that_present_description) {
      if (!(this_present_description && that_present_description))
        return false;
      if (!this.description.equals(that.description))
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_dateBegin = true;
    boolean that_present_dateBegin = true;
    if (this_present_dateBegin || that_present_dateBegin) {
      if (!(this_present_dateBegin && that_present_dateBegin))
        return false;
      if (this.dateBegin != that.dateBegin)
        return false;
    }

    boolean this_present_dateEnd = true;
    boolean that_present_dateEnd = true;
    if (this_present_dateEnd || that_present_dateEnd) {
      if (!(this_present_dateEnd && that_present_dateEnd))
        return false;
      if (this.dateEnd != that.dateEnd)
        return false;
    }

    boolean this_present_dateCreated = true;
    boolean that_present_dateCreated = true;
    if (this_present_dateCreated || that_present_dateCreated) {
      if (!(this_present_dateCreated && that_present_dateCreated))
        return false;
      if (this.dateCreated != that.dateCreated)
        return false;
    }

    boolean this_present_userCreated = true && this.isSetUserCreated();
    boolean that_present_userCreated = true && that.isSetUserCreated();
    if (this_present_userCreated || that_present_userCreated) {
      if (!(this_present_userCreated && that_present_userCreated))
        return false;
      if (!this.userCreated.equals(that.userCreated))
        return false;
    }

    boolean this_present_dateModified = true;
    boolean that_present_dateModified = true;
    if (this_present_dateModified || that_present_dateModified) {
      if (!(this_present_dateModified && that_present_dateModified))
        return false;
      if (this.dateModified != that.dateModified)
        return false;
    }

    boolean this_present_userModified = true && this.isSetUserModified();
    boolean that_present_userModified = true && that.isSetUserModified();
    if (this_present_userModified || that_present_userModified) {
      if (!(this_present_userModified && that_present_userModified))
        return false;
      if (!this.userModified.equals(that.userModified))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TPromotionValue other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TPromotionValue typedOther = (TPromotionValue)other;

    lastComparison = Boolean.valueOf(isSetPromotionId()).compareTo(typedOther.isSetPromotionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromotionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promotionId, typedOther.promotionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPromotionRateData()).compareTo(typedOther.isSetPromotionRateData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromotionRateData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promotionRateData, typedOther.promotionRateData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPromotionUserGroup()).compareTo(typedOther.isSetPromotionUserGroup());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromotionUserGroup()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promotionUserGroup, typedOther.promotionUserGroup);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPromotionName()).compareTo(typedOther.isSetPromotionName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPromotionName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.promotionName, typedOther.promotionName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPriority()).compareTo(typedOther.isSetPriority());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriority()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priority, typedOther.priority);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDescription()).compareTo(typedOther.isSetDescription());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDescription()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.description, typedOther.description);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(typedOther.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, typedOther.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDateBegin()).compareTo(typedOther.isSetDateBegin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDateBegin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dateBegin, typedOther.dateBegin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDateEnd()).compareTo(typedOther.isSetDateEnd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDateEnd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dateEnd, typedOther.dateEnd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDateCreated()).compareTo(typedOther.isSetDateCreated());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDateCreated()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dateCreated, typedOther.dateCreated);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserCreated()).compareTo(typedOther.isSetUserCreated());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserCreated()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userCreated, typedOther.userCreated);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDateModified()).compareTo(typedOther.isSetDateModified());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDateModified()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dateModified, typedOther.dateModified);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserModified()).compareTo(typedOther.isSetUserModified());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserModified()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userModified, typedOther.userModified);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TPromotionValue(");
    boolean first = true;

    sb.append("promotionId:");
    sb.append(this.promotionId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("promotionRateData:");
    if (this.promotionRateData == null) {
      sb.append("null");
    } else {
      sb.append(this.promotionRateData);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("promotionUserGroup:");
    if (this.promotionUserGroup == null) {
      sb.append("null");
    } else {
      sb.append(this.promotionUserGroup);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("promotionName:");
    if (this.promotionName == null) {
      sb.append("null");
    } else {
      sb.append(this.promotionName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("priority:");
    sb.append(this.priority);
    first = false;
    if (!first) sb.append(", ");
    sb.append("description:");
    if (this.description == null) {
      sb.append("null");
    } else {
      sb.append(this.description);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dateBegin:");
    sb.append(this.dateBegin);
    first = false;
    if (!first) sb.append(", ");
    sb.append("dateEnd:");
    sb.append(this.dateEnd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("dateCreated:");
    sb.append(this.dateCreated);
    first = false;
    if (!first) sb.append(", ");
    sb.append("userCreated:");
    if (this.userCreated == null) {
      sb.append("null");
    } else {
      sb.append(this.userCreated);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dateModified:");
    sb.append(this.dateModified);
    first = false;
    if (!first) sb.append(", ");
    sb.append("userModified:");
    if (this.userModified == null) {
      sb.append("null");
    } else {
      sb.append(this.userModified);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TPromotionValueStandardSchemeFactory implements SchemeFactory {
    public TPromotionValueStandardScheme getScheme() {
      return new TPromotionValueStandardScheme();
    }
  }

  private static class TPromotionValueStandardScheme extends StandardScheme<TPromotionValue> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TPromotionValue struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROMOTION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.promotionId = iprot.readI32();
              struct.setPromotionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROMOTION_RATE_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.promotionRateData = iprot.readString();
              struct.setPromotionRateDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROMOTION_USER_GROUP
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.promotionUserGroup = com.bliss.service.thrift.EEventUserGroup.findByValue(iprot.readI32());
              struct.setPromotionUserGroupIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PROMOTION_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.promotionName = iprot.readString();
              struct.setPromotionNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PRIORITY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.priority = iprot.readI32();
              struct.setPriorityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DESCRIPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.description = iprot.readString();
              struct.setDescriptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = EStatus.findByValue(iprot.readI32());
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // DATE_BEGIN
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.dateBegin = iprot.readI64();
              struct.setDateBeginIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // DATE_END
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.dateEnd = iprot.readI64();
              struct.setDateEndIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // DATE_CREATED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.dateCreated = iprot.readI64();
              struct.setDateCreatedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // USER_CREATED
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userCreated = iprot.readString();
              struct.setUserCreatedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // DATE_MODIFIED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.dateModified = iprot.readI64();
              struct.setDateModifiedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // USER_MODIFIED
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userModified = iprot.readString();
              struct.setUserModifiedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TPromotionValue struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PROMOTION_ID_FIELD_DESC);
      oprot.writeI32(struct.promotionId);
      oprot.writeFieldEnd();
      if (struct.promotionRateData != null) {
        oprot.writeFieldBegin(PROMOTION_RATE_DATA_FIELD_DESC);
        oprot.writeString(struct.promotionRateData);
        oprot.writeFieldEnd();
      }
      if (struct.promotionUserGroup != null) {
        oprot.writeFieldBegin(PROMOTION_USER_GROUP_FIELD_DESC);
        oprot.writeI32(struct.promotionUserGroup.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.promotionName != null) {
        oprot.writeFieldBegin(PROMOTION_NAME_FIELD_DESC);
        oprot.writeString(struct.promotionName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PRIORITY_FIELD_DESC);
      oprot.writeI32(struct.priority);
      oprot.writeFieldEnd();
      if (struct.description != null) {
        oprot.writeFieldBegin(DESCRIPTION_FIELD_DESC);
        oprot.writeString(struct.description);
        oprot.writeFieldEnd();
      }
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        oprot.writeI32(struct.status.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DATE_BEGIN_FIELD_DESC);
      oprot.writeI64(struct.dateBegin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DATE_END_FIELD_DESC);
      oprot.writeI64(struct.dateEnd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DATE_CREATED_FIELD_DESC);
      oprot.writeI64(struct.dateCreated);
      oprot.writeFieldEnd();
      if (struct.userCreated != null) {
        oprot.writeFieldBegin(USER_CREATED_FIELD_DESC);
        oprot.writeString(struct.userCreated);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DATE_MODIFIED_FIELD_DESC);
      oprot.writeI64(struct.dateModified);
      oprot.writeFieldEnd();
      if (struct.userModified != null) {
        oprot.writeFieldBegin(USER_MODIFIED_FIELD_DESC);
        oprot.writeString(struct.userModified);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TPromotionValueTupleSchemeFactory implements SchemeFactory {
    public TPromotionValueTupleScheme getScheme() {
      return new TPromotionValueTupleScheme();
    }
  }

  private static class TPromotionValueTupleScheme extends TupleScheme<TPromotionValue> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TPromotionValue struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPromotionId()) {
        optionals.set(0);
      }
      if (struct.isSetPromotionRateData()) {
        optionals.set(1);
      }
      if (struct.isSetPromotionUserGroup()) {
        optionals.set(2);
      }
      if (struct.isSetPromotionName()) {
        optionals.set(3);
      }
      if (struct.isSetPriority()) {
        optionals.set(4);
      }
      if (struct.isSetDescription()) {
        optionals.set(5);
      }
      if (struct.isSetStatus()) {
        optionals.set(6);
      }
      if (struct.isSetDateBegin()) {
        optionals.set(7);
      }
      if (struct.isSetDateEnd()) {
        optionals.set(8);
      }
      if (struct.isSetDateCreated()) {
        optionals.set(9);
      }
      if (struct.isSetUserCreated()) {
        optionals.set(10);
      }
      if (struct.isSetDateModified()) {
        optionals.set(11);
      }
      if (struct.isSetUserModified()) {
        optionals.set(12);
      }
      oprot.writeBitSet(optionals, 13);
      if (struct.isSetPromotionId()) {
        oprot.writeI32(struct.promotionId);
      }
      if (struct.isSetPromotionRateData()) {
        oprot.writeString(struct.promotionRateData);
      }
      if (struct.isSetPromotionUserGroup()) {
        oprot.writeI32(struct.promotionUserGroup.getValue());
      }
      if (struct.isSetPromotionName()) {
        oprot.writeString(struct.promotionName);
      }
      if (struct.isSetPriority()) {
        oprot.writeI32(struct.priority);
      }
      if (struct.isSetDescription()) {
        oprot.writeString(struct.description);
      }
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status.getValue());
      }
      if (struct.isSetDateBegin()) {
        oprot.writeI64(struct.dateBegin);
      }
      if (struct.isSetDateEnd()) {
        oprot.writeI64(struct.dateEnd);
      }
      if (struct.isSetDateCreated()) {
        oprot.writeI64(struct.dateCreated);
      }
      if (struct.isSetUserCreated()) {
        oprot.writeString(struct.userCreated);
      }
      if (struct.isSetDateModified()) {
        oprot.writeI64(struct.dateModified);
      }
      if (struct.isSetUserModified()) {
        oprot.writeString(struct.userModified);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TPromotionValue struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(13);
      if (incoming.get(0)) {
        struct.promotionId = iprot.readI32();
        struct.setPromotionIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.promotionRateData = iprot.readString();
        struct.setPromotionRateDataIsSet(true);
      }
      if (incoming.get(2)) {
        struct.promotionUserGroup = com.bliss.service.thrift.EEventUserGroup.findByValue(iprot.readI32());
        struct.setPromotionUserGroupIsSet(true);
      }
      if (incoming.get(3)) {
        struct.promotionName = iprot.readString();
        struct.setPromotionNameIsSet(true);
      }
      if (incoming.get(4)) {
        struct.priority = iprot.readI32();
        struct.setPriorityIsSet(true);
      }
      if (incoming.get(5)) {
        struct.description = iprot.readString();
        struct.setDescriptionIsSet(true);
      }
      if (incoming.get(6)) {
        struct.status = EStatus.findByValue(iprot.readI32());
        struct.setStatusIsSet(true);
      }
      if (incoming.get(7)) {
        struct.dateBegin = iprot.readI64();
        struct.setDateBeginIsSet(true);
      }
      if (incoming.get(8)) {
        struct.dateEnd = iprot.readI64();
        struct.setDateEndIsSet(true);
      }
      if (incoming.get(9)) {
        struct.dateCreated = iprot.readI64();
        struct.setDateCreatedIsSet(true);
      }
      if (incoming.get(10)) {
        struct.userCreated = iprot.readString();
        struct.setUserCreatedIsSet(true);
      }
      if (incoming.get(11)) {
        struct.dateModified = iprot.readI64();
        struct.setDateModifiedIsSet(true);
      }
      if (incoming.get(12)) {
        struct.userModified = iprot.readString();
        struct.setUserModifiedIsSet(true);
      }
    }
  }

}

